### ISSUE TITLE
After I use it normally, it doesn't work in laravel 5.5. What's the problem

### ISSUE THREAD

**Issue by niyelail** [staudenmeir/eloquent-param-limit-fix#5]
After I use it normally, it doesn't work in laravel 5.5. What's the problem
![image](https://user-images.githubusercontent.com/44046932/105277431-5e6cfb80-5bde-11eb-9d43-762d50a294f5.png)
![image](https://user-images.githubusercontent.com/44046932/105277483-76447f80-5bde-11eb-85d2-8e853e828d24.png)
![image](https://user-images.githubusercontent.com/44046932/105277497-7d6b8d80-5bde-11eb-8ce9-2bc198ab1b20.png)

**Comment by staudenmeir** [comment]
What exactly doesn't work?
