### ISSUE TITLE
Having trouble getting the trait to work

### ISSUE THREAD

**Issue by benjivm** [staudenmeir/eloquent-param-limit-fix#7]
Hi! This looks like exactly what I need, but I keep hitting the `SQLSTATE[IMSSP]: Tried to bind parameter number 2101.` error. Here's my implementation:

Base model, all models that use the MSSQL connection in my project extend this:

```php
use Illuminate\Database\Eloquent\Model;
use Staudenmeir\EloquentParamLimitFix\ParamLimitFix;

class BaseModel extends Model
{
    use ParamLimitFix;

    protected $connection = 'sqlsrv';
}
```

Specific model that is triggering the issue:
```php
class Part extends BaseModel
{
    protected $table = 'dbo.Part';

    protected $primaryKey = 'PartNum';

    protected $keyType = 'string';

    public $incrementing = false;

    protected $casts = [
        'UnitPrice' => 'float',
        'SparePart_c' => 'boolean',
        'InActive' => 'boolean',
        'WebPart' => 'boolean',
        'OnHold' => 'boolean',
    ];

    protected static function booted(): void
    {
        static::addGlobalScope(new PartClassScope());
        static::addGlobalScope(
            new SelectScope([
                'PartNum',
                'PartDescription',
                'TypeCode',
                'ClassID',
                'UnitPrice',
                'SparePart_c',
                'SubPart',
                'OnHold',
                'OnHoldReasonCode',
                'InActive',
                'WebPart',
            ])
        );
    }
// ...
```

Relationship on queried model (`Node.php`, references above model):
```php
class Node extends Model
{
    use HasFactory;
    use HasRecursiveRelationships;
// ...
    public function part(): BelongsTo
    {
        return $this->belongsTo(Part::class);
    }
// ...
```

Eager loading:
```php
public function show(Bom $bom)
{
    $nodes = Node::query()
        ->bom($bom->id)
        ->visible()
        ->with([
            'part',
            'section',
            'type',
            'ancestors',
            'descendants',
        ])
        ->get();
// ...
```

Now, the `Node` model is not on the same connection as the `Part` model--the nodes are stored in a PostgreSQL database-- however this relationship works with all `Node`s with < 2100 `Part` relationships.

Another thing is that the `Builder` provided by the trait does not appear to be getting invoked at all, is this because I am trying to load the relationship from a parent model (`Node`) that does not use it? I did try adding it to the Node model but wasn't able to get that to work either.

Thanks for your time.

**Comment by staudenmeir** [comment]
Hi @benjivm,

> is this because I am trying to load the relationship from a parent model (Node) that does not use it?

Indeed, the trait needs to be on the parent model. The issue is that it conflicts with `HasRecursiveRelationships` because they both override the `newEloquentBuilder()` method.

I've created a package that merges these two traits:
https://github.com/staudenmeir/eloquent-param-limit-fix-x-laravel-adjacency-list

**Comment by benjivm** [comment]
I added that trait to the `Node` model but still have no luck because the root connection is Postgres, and the MSSQL is loaded from the relationship (which the trait doesn't check). I did the following and it works:

BuildsParamLimitFixQueries.php:
```php
trait BuildsParamLimitFixQueries
{
    /**
     * The maximum number of parameters per query.
     *
     * The values are lower than the actual limits
     * to have a margin for polymorphic relationships
     * and other query parameters.
     *
     * @var array
     */
    protected $parameterLimits = [
        MySqlConnection::class => 65000,
        SQLiteConnection::class => 900,
        SqlServerConnection::class => 2000,
        PostgresConnection::class => 2000, // added this to manually force chunking
    ];
```

Is there a way for the Builder to detect if another connection is being used and apply the proper chunks, or perhaps a supported way to manually specify the `$parameterLimits[]`?

**Comment by staudenmeir** [comment]
I'll look into it.

**Comment by staudenmeir** [comment]
> Is there a way for the Builder to detect if another connection is being used and apply the proper chunks

Unfortunately, this is quite complex. 

> or perhaps a supported way to manually specify the $parameterLimits[]

You need to create your custom `Builder` class (e.g. in `app/Builder.php`):

```php
<?php

namespace App;

use Illuminate\Database\MySqlConnection;
use Illuminate\Database\PostgresConnection;
use Illuminate\Database\SQLiteConnection;
use Illuminate\Database\SqlServerConnection;
use Staudenmeir\EloquentParamLimitFixXLaravelAdjacencyList\Eloquent\Builder as Base;

class Builder extends Base
{
    protected $parameterLimits = [
        MySqlConnection::class => 65000,
        SQLiteConnection::class => 900,
        SqlServerConnection::class => 2000,
        PostgresConnection::class => 2000, // added this to manually force chunking
    ];
}
```

Then use it in your model:

```php
use App\Builder;
use Staudenmeir\EloquentParamLimitFixXLaravelAdjacencyList\Eloquent\HasParamLimitFixAndRecursiveRelationships;

class Node extends Model
{
   use HasParamLimitFixAndRecursiveRelationships;

    public function newEloquentBuilder($query)
    {
        return new Builder($query);
    }
}
```

**Comment by benjivm** [comment]
@staudenmeir Understood, thanks for your help and work!
