### ISSUE TITLE
Is it possible to use this package without eager loading?

### ISSUE THREAD

**Issue by ryanmortier** [staudenmeir/eloquent-param-limit-fix#8]
I'm trying to select greater than 2100 accounts for a bulk action on a table and running into the SQL Server parameter limit.

It's not eager loading a relationship, just running into the issue with the main query itself.

![CleanShot 2024-03-05 at 16 18 34](https://github.com/staudenmeir/eloquent-param-limit-fix/assets/2053960/847da467-95ee-47cd-873c-0926363bf503)

**Comment by staudenmeir** [comment]
Hi @ryanmortier,
What does your query look like?

**Comment by ryanmortier** [comment]
> Hi @ryanmortier, What does your query look like?

```sql
select *
from [crm].[accounts]
where [crm].[accounts].[id] in (
    31LC01, ABEG01, ABGE01, ABOG01, ABWA01, ACEWAN, ADAD01, ADAD02, ADAG01, ADAP01, ADAS01, ADEM001, 
    ADEM002, ADMI01, ADMM01, ADMM02, ADVM01, AGCA02, AGINN01, AGRC02, AGRE01, AGRILAB, AGRISAC, AGRM01, 
    AGRM02, AGRO01, AGWO01, AING01, AIRL01, AJ001, etc...
) and ([active] = 1)
order by [name] asc
```

> SQLSTATE[IMSSP]: Tried to bind parameter number 2101. SQL Server supports a maximum of 2100 parameters.

**Comment by staudenmeir** [comment]
You can't use the package for this, but the package's logic is basically an `array_chunk()` call.

Something like this:

```php
use Illuminate\Database\Eloquent\Collection;

$accounts = [];

foreach (array_chunk($ids, 2099) as $chunk) {
    $accounts = array_merge($accounts, Account::whereKey($chunk)->where('active', 1)->get()->all());
}

$accounts = new Collection($accounts);

$accounts = $accounts->sortBy('name')
```

**Comment by ryanmortier** [comment]
Ok thanks!
